import React, { createContext, useContext, useState, useEffect } from 'react';
import { getOrCreateAutoUser } from '../utils/autoUser';

interface User {
  userId: string;
  username: string;
  autoGenerated?: boolean;
  createdAt?: string;
  usernameUpdated?: string;
}

interface UserContextType {
  user: User | null;
  setUser: (user: User | null) => void;
  updateUsername: (newUsername: string) => void;
}

const UserContext = createContext<UserContextType | undefined>(undefined);

export const UserProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [user, setUser] = useState<User | null>(() => {
    // Automatically get or create user on initialization
    return getOrCreateAutoUser();
  });

  useEffect(() => {
    // Ensure user is always set
    if (!user) {
      setUser(getOrCreateAutoUser());
    }
  }, [user]);

  useEffect(() => {
    if (user) {
      localStorage.setItem('musicTriviaUser', JSON.stringify(user));
    } else {
      localStorage.removeItem('musicTriviaUser');
    }
  }, [user]);

  const updateUsername = (newUsername: string) => {
    if (user) {
      const updatedUser = {
        ...user,
        username: newUsername,
        usernameUpdated: new Date().toISOString()
      };
      setUser(updatedUser);
    }
  };

  return (
    <UserContext.Provider value={{ user, setUser, updateUsername }}>
      {children}
    </UserContext.Provider>
  );
};

export const useUser = () => {
  const context = useContext(UserContext);
  if (context === undefined) {
    throw new Error('useUser must be used within a UserProvider');
  }
  return context;
};
