/**
 * Browser-based User Identification Utility
 * Generates a unique, persistent user ID based on browser characteristics
 */

/**
 * Generate a unique browser fingerprint
 */
const generateBrowserFingerprint = (): string => {
  // Collect browser characteristics
  const nav = window.navigator;
  const screen = window.screen;
  
  const components = [
    nav.userAgent,
    nav.language,
    screen.colorDepth,
    screen.width + 'x' + screen.height,
    new Date().getTimezoneOffset(),
    !!window.sessionStorage,
    !!window.localStorage,
  ];
  
  // Create a hash from components
  const fingerprint = components.join('|');
  
  // Simple hash function
  let hash = 0;
  for (let i = 0; i < fingerprint.length; i++) {
    const char = fingerprint.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash; // Convert to 32bit integer
  }
  
  return Math.abs(hash).toString(36);
};

/**
 * Generate a random display name
 */
const generateDisplayName = (): string => {
  const adjectives = [
    'Cool', 'Epic', 'Swift', 'Brave', 'Bright', 'Clever', 'Funky',
    'Groovy', 'Happy', 'Jazz', 'Lucky', 'Mega', 'Noble', 'Quick',
    'Rock', 'Smooth', 'Super', 'Ultra', 'Vivid', 'Wild'
  ];
  
  const nouns = [
    'Cat', 'Tiger', 'Eagle', 'Phoenix', 'Dragon', 'Wolf', 'Fox',
    'Panther', 'Hawk', 'Lion', 'Bear', 'Falcon', 'Raven', 'Jaguar',
    'Viper', 'Cobra', 'Lynx', 'Puma', 'Shark', 'Orca'
  ];
  
  const adjective = adjectives[Math.floor(Math.random() * adjectives.length)];
  const noun = nouns[Math.floor(Math.random() * nouns.length)];
  const number = Math.floor(Math.random() * 9999);
  
  return `${adjective}${noun}${number}`;
};

/**
 * Get or create an automatic user based on browser fingerprint
 */
export const getOrCreateAutoUser = () => {
  const STORAGE_KEY = 'musicTriviaUser';
  
  // Check if user already exists
  const existingUser = localStorage.getItem(STORAGE_KEY);
  if (existingUser) {
    try {
      return JSON.parse(existingUser);
    } catch (e) {
      // Invalid data, will regenerate
    }
  }
  
  // Generate new user - just the ID, no visible username
  const fingerprint = generateBrowserFingerprint();
  
  const newUser = {
    userId: `user_${fingerprint}_${Date.now()}`,
    username: '', // Empty by default - user can set it if they want
    autoGenerated: true,
    createdAt: new Date().toISOString(),
  };
  
  // Save to localStorage
  localStorage.setItem(STORAGE_KEY, JSON.stringify(newUser));
  
  return newUser;
};

/**
 * Update username while keeping the same user ID
 */
export const updateUsername = (newUsername: string) => {
  const STORAGE_KEY = 'musicTriviaUser';
  const existingUser = localStorage.getItem(STORAGE_KEY);
  
  if (existingUser) {
    try {
      const user = JSON.parse(existingUser);
      user.username = newUsername;
      user.usernameUpdated = new Date().toISOString();
      localStorage.setItem(STORAGE_KEY, JSON.stringify(user));
      return user;
    } catch (e) {
      // Error, return null
    }
  }
  
  return null;
};

/**
 * Clear user data (for logout/reset)
 */
export const clearUserData = () => {
  localStorage.removeItem('musicTriviaUser');
};
